name: Deploy to Endora (FictionalExibitionBS)
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # pokud nasazuješ build (např. Vite/React), změň na: local-dir: ./dist/
      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21

          # => nahrávej do /robin-lassak.cz/web/GuessMyNumberJS/
          server-dir: ${{ secrets.FTP_DIR }}GuessMyNumberJS/

          # co odesílat z repa (root). Potřebuješ-li jen podsložku, změň na např. ./site/ nebo ./dist/
          local-dir: ./

          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
